cwendt94/espn-api

README.md
ff_espn_api/league.py
ff_espn_api/utils.py
tests/unit/test_league.py

Implements power ranking feature from espnff #9

Feature power ranking#9

---

espn_api/football/box_player.py
espn_api/football/box_score.py
espn_api/football/constant.py

I found the codes for the points breakdown in this JS library ([repo](https://github.com/mkreiser/ESPN-Fantasy-Football-API),  [stat codes](https://github.com/mkreiser/ESPN-Fantasy-Football-API/blob/master/src/player-stats/player-stats.js)) and added them into the box player class. I think they are correct and seem to make sense for the various player/positions that I checked.
I manually added the Head Coach and Punter codes (my league has some wacky positions...)
also updated the `box_score.__repr__` to print out some useful info 
closes #80

Add points breakdown

---

espn_api/base_league.py

Adds a condition to check for scoring periods that have an empty list value when parsing the espn_request.get_pro_schedule() response #140

Fix box_scores IndexError issue caused by rescheduled game

---

espn_api/base_league.py
espn_api/football/league.py
tests/football/unit/test_league.py

Adds public function to get the latest league data (Team's roster, standings, settings, current week) without having to recreate the League Class #132

Refresh League without creating new object

---

espn_api/basketball/constant.py
espn_api/basketball/player.py

The `lineupSlotId` field represents the slot in the team lineup that a player occupies during the current matchup. This information may be useful for optimizing lineups or predicting matchup outcomes.
I verified this change against my team in a private league, but I'm not sure if there are any other steps I should take—let me know if I missed anything 😄 
```python
>>> for player in my_team.roster:
...     print("{:>2} {}".format(player.lineupSlot, player.name))
... 
SG James Harden
IR Jimmy Butler
C Nikola Vucevic
PG Kyle Lowry
G D'Angelo Russell
UT Brook Lopez
PF Lauri Markkanen
UT Devonte' Graham
IR Kevin Love
BE Rui Hachimura
BE Darius Bazley
SF Keldon Johnson
F Robert Covington
BE DeAndre Jordan
UT Delon Wright
```

Add lineupSlot to basketball Player object

---

espn_api/basketball/box_player.py
espn_api/basketball/box_score.py
espn_api/basketball/league.py
tests/basketball/integration/test_league.py

New `box_score` interface that takes two optional parameters `matchup_period` and `scoring_period`.
If `matchup_period` is passed: It will return the Box Score Class with the total points and total player points for that whole matchup across multiple games.
If `scoring_period` is passed: It will return the Box Score Class for that scoring period (usually a single day) and the points and player points will reflect that single scoring period.
If none of the parameters are passed: It will return the Box Score Class for the current matchup and scoring period with total points and player points up to the scoring period.

Basketball Box Score

---

espn_api/baseball/box_score.py
espn_api/baseball/constant.py
espn_api/baseball/league.py
tests/baseball/integration/test_league.py

I added retrieving box scores for baseball leagues that are head to head categories.
I also cleaned up some of the stat mappings (names and also the comments about them). I used the stats abbreviations from the glossary at the bottom of ESPN stat pages (see https://www.espn.com/mlb/player/stats/_/id/28976/max-scherzer for example).
The only semantic change is for stat `53` which was marked as `QS` (quality starts) but I am certain is `W` (wins), based on examining the box scores from my own league. I removed `63` which was previously `W`.

Baseball: add getting box scores for categories

---

espn_api/baseball/constant.py
espn_api/baseball/player.py

I found a few players that had a position id of 21 in their `eligibleSlots`. They were all players in the minor leagues, almost entire players drafter last year. I don't know what 21 could possibly correspond to, so it seems like a more general solution to allow the position id to pass through without translation if it's not in the mapping. The existing `POSITION_MAP` mapping seems complete to me so I don't think we're really missing anything by not mapping 18, 21, or 22.
Examples of players with an `eligibleSlots` of 21 are Austin Hendrick, Luis Matos, Blaze Jordan, and Carlos Colmenarez.

Baseball: ignore unknown player positions

---

espn_api/basketball/box_player.py
espn_api/basketball/box_score.py
espn_api/basketball/constant.py
espn_api/basketball/league.py
espn_api/basketball/player.py
espn_api/basketball/team.py
espn_api/requests/__init__.py

Basketball Add Total, Avg and Projected Points to Player Object for #281 
Updates stats map key for readability

Basketball Add Total, Avg and Projected Points to Player Object

---

espn_api/hockey/league.py

I was getting the following error when doing `league = League(league_id=LEAGUE_ID, year=2022, swid=SWID, espn_s2=ESPN_S2, debug=True)`
```
Traceback (most recent call last):
File "main.py", line 11, in <module>
f()
File ".../espn-api/main.py", line 7, in f
league = League(league_id=LEAGUE_ID, year=2022, swid=SWID, espn_s2=ESPN_S2, debug=True)
File ".../espn-api/espn_apii/hockey/league.py", line 22, in __init__
data = self._fetch_league()
File ".../espn-api/espn_api/hockey/league.py", line 30, in _fetch_league
self._map_matchup_ids(data['schedule'])
File ".../espn-api/espn_api/hockey/league.py", line 39, in _map_matchup_ids
scoring_periods = match['home'].get('pointsByScoringPeriod', {}).keys()
KeyError: 'home'
```
I noticed that the code for basketball leagues was doing `match.get('home', …

add default for hockey league data['schedule']['home']

---

espn_api/baseball/constant.py

This was found by checking the data returned by API calls against the stats in my league.

Add SVHD and QS to baseball STATS_MAP

---

espn_api/football/box_score.py
espn_api/football/matchup.py

`is_playoff` flag and `matchup_type` is added to box score and matchup classes. `matchup_type` will be set to `NONE` for regular games and then for playoffs it can be `WINNERS_BRACKET` `LOSERS_CONSOLATION_LADDER` `WINNERS_CONSOLATION_LADDER` and `LOSERS_CONSOLATION_LADDER`. There could possibly be more as these are the only ones I see in one of my leagues data.
#337

Add matchup type and is playoff

---

espn_api/baseball/league.py
espn_api/basketball/league.py
espn_api/football/league.py
espn_api/hockey/league.py
espn_api/wbasketball/league.py
tests/baseball/integration/test_league.py
tests/basketball/integration/test_league.py
tests/football/integration/test_league.py
tests/hockey/integration/test_league.py
tests/wbasketball/integration/test_league.py

** Parameter "fetch_league" defaults to True but when a user selects or passes
False the data fetching will be handled later.
** Added a public "fetch_league" function to handle the explicit data fetching and expose the function to users. This does not appear in the base class
** Added tests for the init of the leagues without fetching data.
#338

Add __init__ parameter to allow leagues to skip the data fetching.

---

espn_api/football/constant.py

Additions (should not impact existing users):
Added stat IDs to fill in gaps within the current constant structure. 
Added acronym for ESPN scoring stats in comment after stat ID (if applicable). 
All ESPN scoring stats (even in custom leagues) should be present with the exception of "stuffs" and 1 point safeties (this has never happened in the NFL).
Added notes for unknown constants based on observations (potentially useful for determining values in the future).
Potentially Breaking Changes:
Swapped fumble and interception return touchdown IDs (these appeared to be incorrect). 
Added "s" to stats 101-104 to note that these values could be > 1. 
Made stat ID 155 start with lowercase name to match other stats.

NFL Added Constants

---

espn_api/base_settings.py

Simple change to add `faab` boolean to league settings to determine if the league is using a free agent acquisition budget

add faab to league settings

---

espn_api/football/constant.py
espn_api/football/league.py
espn_api/football/settings.py
tests/football/unit/test_league.py

Adds scoring format to football league settings #84

Fb settings scoring format

---

espn_api/football/team.py

* I discovered a bug which caused the intialization of the league object to crash.
* I believe this occurred because in my league we have an odd number of teams which results in one matchup each week having only one team and that team always appears to be the away team, 
When creating the outcomes object the code looks for the home and away keys even though they may not exist in the matchup object in a league with an odd number of teams. 
This PR adds a check to ensure the home key exists prior to lookup to avoid a crash. 
Here was the error I received, prior to implementing the fix.  
```
python3 main.py                                                                                                                                                                              ─╯
Traceback …
```

fix: Verify home key exists when querying for matchup data

---

espn_api/basketball/player.py

Prevents stats from being pulled from games in previous years. This could occur when a player had games with the same `scoringPeriodId` in multiple years

Only grab player stats for specified year

---

espn_api/basketball/league.py
espn_api/basketball/pick.py

Implements draft support for basketball. Copied over from the football implementation. Only change is the string representation in order to better display the round and pick number.
This should probably be moved to a base pick class, similar to what is planned for players with #124 , but this should do for now. Might also be worth considering adding a player object member instead of the separate name and id-- similar to how the team member is a team object

Add draft support for basketball

---

espn_api/utils/logger.py

related to [discussion](https://github.com/cwendt94/espn-api/discussions/436). feel free to decline if it doesn't meet all use cases.

log output as json

---

espn_api/football/league.py
espn_api/requests/espn_requests.py

Football League message board #429

Football League Message Board

---

espn_api/basketball/constant.py
espn_api/basketball/player.py
tests/basketball/integration/test_league.py

This adds a property to Player that shows the yearly averages for common categories used in 9-cat leagues.
I've been really liking using this library to do some more digging into my league, and it'll be great to get easier access to category averages. So this PR gets closer to that, but let me know if there are any issues with adding this. Thanks!

Add yearly nine_cat_averages to Player

---

espn_api/baseball/league.py
espn_api/basketball/league.py
espn_api/football/league.py
espn_api/hockey/league.py
espn_api/wbasketball/league.py

Adds an optional parameter to support `offset` in the `recent_activity` method on `League`. 
The benefit of this is the code for retrieving recent activity (1000 events in my example) can be more finely controlled.
```python
league = League(...)
activity = league.recent_activity(1000)
```
is now
```python
league = League(...)
offset = 0
limit = 25
for True: # Implement a stopping condition
activity = league.recent_activity(limit=limit, offset=offset)
offset += limit
```
Looks like my editor also removed some blank space, I can add that back if it makes the PR tougher to read.

adding an offset parameter to support paging through all activities

---

espn_api/football/league.py
espn_api/football/matchup.py

This PR adds a `Team` type annotation for the `Matchup` class. Currently, the id is written (as an int) and then in a loop it is dynamically changed to a `Team`. I made a change to store the id in a separate variable `_{home,away}_team_id` and then uses that variable in the loop to set the `team`. I noticed this 'issue' while working in VS Code and the type annotation wasn't populating, this should make for a slightly improved developer experience

Adding type annotation for the scoreboard method

---

espn_api/base_league.py
espn_api/baseball/team.py
espn_api/basketball/team.py
espn_api/football/team.py
espn_api/hockey/team.py
espn_api/wbasketball/team.py
tests/hockey/unit/test_team.py

Currently there's no way to get info on the "owner" (aka "manager") of a Team.  While the team's name is available, those are subject to change making tracking over longer periods difficult
ESPN has a concept of Members on a League and Owners on a Team.  These are tied together by an Id and the Member entity has much more stable information about the actual humans behind the team.
Storing this Member info with the Team will make that info more accessible
* added members property to the League
* modified BaseLeague fetch_teams to create and an array of members associated with the owners of each Team
* added owners property and constructor parameter to Teams

adding owners to Team

---

espn_api/football/player.py

This PR can finally resolve a long-standing issue... historical injury status! For a while now, an issue (https://github.com/cwendt94/espn-api/issues/327, https://github.com/cwendt94/espn-api/issues/401) we've had is that ESPN only return's a player's current health status, even when querying a previous week or year. I think I have a way to get around this and assume a player's health status from previous weeks.
This uses the embedded stats objects to decipher whether a player was active in a historical week.
* `active`: the player had a game and participated in it
* `inactive`: the player had a game but did not participate in it (due to injury or suspension)
* `bye`: the player did not have a game that week
Testing and research can be viewed …

feat: Add active status to `Player`

---

espn_api/hockey/constant.py
espn_api/hockey/player.py

Hockey positions don't hold the same key:value relationship between the `eligibleSlots` and `lineupSlot` fields and the `position` field under player.py. 
Modified constant.py to match the `eligibleSlots ` and `lineupSlot` values (which has an extra 'Forward' value) and reconfigured the Player() init to account for the mismatch in keys.

Update hockey positions

---

espn_api/base_league.py

Add a list of all previous seasons for a league. I know this is accurate for football leagues, and I assume(?) this is the same across all ESPN leagues and should be a part of the `BaseLeague` object.

feat: Add `previousSeasons` to `BaseLeague` object

---

espn_api/base_league.py
espn_api/baseball/team.py
espn_api/basketball/team.py
espn_api/football/team.py
espn_api/hockey/team.py
espn_api/wbasketball/team.py

feat: #497
Team.owners will now be an array of dict. It will look like
```
{ id: '1234', displayName: 'team', firstName: 'Bob', lastName: 'Joe'}
```
However in public leagues, the name attributes will not be populated.

feat: Add full owner info to team

---

espn_api/football/helper.py
espn_api/football/league.py
tests/football/unit/test_league.py

This PR is to replace [another attempt](https://github.com/cwendt94/espn-api/pull/513).  
The tiebreaking process is quite complicated, but this follows all tiebreaking levels, subject to a league's specific tiebreaker rules.

feat: Add method to calculate historical standings for any week

---

espn_api/base_league.py

fixes #518 
Fixes edge case, where if team has the key 'owners' but its value is None or an empty list, this will raise an IndexError. It will now properly make an empty list with an indexable [0] element

Edge case "None" owners fix

---

espn_api/football/settings.py

In the context of a **draft**, it's useful to know how many slots are available for each position.  Within the API, this information is available as part of the `mSettings` view:
```
// psuedo-JSON response
{
.... 
rosterSettings: {
... 
lineupSlotCounts: {
"0": 1, // maps to "QB" slot 
"1": 0, // maps to "TQB" slot
"2": 2, // maps to "RB" slot
... etc, goes all the way to slot 24
}
}
}
```
We can map each lineupSlotCount(s) to it's respective position and provide this information to the consumer:
```
from espn_api.football import League
league = League(...)
print(league.settings.position_slot_counts)
```

Add slot positions from roster settings

---

espn_api/football/league.py

If we need to run in-step with a live draft, we need a short circuit to retrieve latest draft state without refreshing the entirety of league state, since refreshing league state can take several seconds.

Refresh Draft function for Football

---

espn_api/requests/constant.py
tests/football/unit/test_league.py
tests/football/unit/test_past_league.py

Update ESPN API Base Endpoint

---

espn_api/football/league.py

We had a team score 93.72 and another 93.0 this week. Using int comparisons allowed least_scored_week() to return 93.72 instead of 93.0 :( . float comparisons fixes this.

least/top scored week should use float, not int

---

espn_api/base_league.py
espn_api/football/league.py
espn_api/football/player.py
espn_api/football/team.py
tests/football/unit/data/pro_schedule_2024.json
tests/football/unit/test_league.py
tests/football/unit/test_past_league.py

Request from #573, adding pro schedule to player class

FB Add Pro Schedule to Player Class

---

espn_api/basketball/activity.py
espn_api/basketball/constant.py
espn_api/basketball/league.py

This adds the moved activity in basketball (player moved to a different fantasy roster slot). It is an optional argument with default value of False so that existing usage is not affected.

Basketball Add Moved as an Optional Output of Activity

---

espn_api/hockey/box_player.py
espn_api/hockey/constant.py

Hockey Add new Team Utah Hockey Club

---

espn_api/basketball/team.py

Porting functionality that already exists in football over to basketball.
https://github.com/cwendt94/espn-api/blob/be5e92b8573d126a7231069742aa07798b952938/espn_api/football/team.py#L18-L21

Add Transaction Info to Basketball Team

---

espn_api/basketball/player.py

Fixed directly calling a potentially missing key in a dict

---

espn_api/basketball/constant.py
espn_api/basketball/league.py
espn_api/basketball/transaction.py
espn_api/basketball/transaction_item.py

New method `League.transactions()` uses the `mTransactions2` view to fetch more detailed transaction data than is available through `recent_activity`.
I'm only fetching free agent and waiver transactions right now because that's the only data I have available to test with in my league, however trades and roster moves are also available. In my testing I got a surprisingly helpful error message that enumerated all available transaction types:
DRAFT, TRADE_ACCEPT, WAIVER, TRADE_VETO, FUTURE_ROSTER, ROSTER, RETRO_ROSTER, TRADE_PROPOSAL, TRADE_UPHOLD, FREEAGENT, TRADE_DECLINE, WAIVER_ERROR, TRADE_ERROR

Basketball League Transactions

---

espn_api/football/matchup.py

If you print a matchup object where there is a bye week, it fails with an error because there is no away team.
This fix assumes that bye weeks will always have a "home team:

Handle bye weeks in matchup string representation

---

espn_api/basketball/league.py
espn_api/basketball/team.py

Very small PR to just add two type hints to the League and Team objects for usability. Found myself very often having to jump into source code to use the objects instead of just relying on IDE type hints.
AFAIK this is backwards compatible to all python versions but if there are specific tests or something to be shown let me know.

Basketball - Add player and team typehints

---

espn_api/basketball/league.py
espn_api/basketball/player.py
espn_api/requests/constant.py
espn_api/requests/espn_requests.py

This adds player news to the player_info function in league.py. Player is then initialized with self.news, which is a dictionary with the date the news was published, the headline, and the story. It works with a single payer or with a list of player Ids. For example this program:
players = league.player_info(playerId=[4701230, 4277956], include_news=True)
for player in players:
print(player.news)
returns this:
[{'published': '2025-01-29T15:41:35Z', 'headline': 'Johnson was diagnosed Wednesday with a torn labrum in his left shoulder and will miss the rest of the season, league sources tell NBA reporter Chris Haynes.', 'story': "After breaking out in his first season as a full-time starter in 2023-24, Johnson had taken another step forward in 2024-25 ...
[{'published': …

Basketball Add Player News

---

espn_api/basketball/player.py

Small commit to add expected return date (from injury) to the player class. It returns a datetime date.
Example:
league.player_info(name="Jalen Johnson").expectedReturnDate)
Return:
2025-01-30
Alternatively if you prefer to keep it simple we could do it in one line:
self.expectedReturnDate = json_parsing(data, 'expectedReturnDate')
And then the same code returns:
[2025, 1, 30]
Just thought it might be nice to return in datetime format but I'm good with it either way.

Basketball add expected return date to player

---

espn_api/football/constant.py
espn_api/football/league.py
espn_api/football/transaction.py

Fixes #576 
Used same implementation that exists within Basketball for Football to grab transactions without needing ESPN_S2 and SWID.
Tested sucessfully 
```
from espn_api.football.league import League
league_id=164483
year=2024
league = League(league_id, year)
transactions = league.transactions(scoring_period=16)
for transaction in transactions:
print(transaction)
```

Add transactions to football
