.gitignore, ff_espn_api/league.py, ff_espn_api/pick.py, ff_espn_api/player.py
Thanks so much for making this, from one grateful python-enthused commisioner to another.
I have some scripts that generated all the keeper choices for my complicated league, and they all broke when ESPN got the face lift.
=> Add auction support, acquisition tracking to player

ff_espn_api/settings.py, tests/unit/data/league_settings_2018.json
Should fix KeyError with deadlineDate field #10
=> Check deadlineDate is in the league trade settings object

ff_espn_api/box_player.py
Fix bug where projected and actual points were switched. #6
=> Use stat source id field for projected and actual points

ff_espn_api/box_player.py, ff_espn_api/league.py, ff_espn_api/team.py, setup.py
=> If the league is not full, some teams will not have owner field

README.md, ff_espn_api/constant.py, ff_espn_api/player.py, setup.py
=> Position map key25#16

README.md, ff_espn_api/constant.py, ff_espn_api/league.py, setup.py, tests/integration/test_league.py, tests/unit/test_league.py
Adding filter features to free agents #18
=> Free agent filters

.travis.yml, ff_espn_api/league.py, setup.py
Should fix #21 for a player not being drafted in a round
=> Key error player not drafted

ff_espn_api/league.py, setup.py
Handle if team owner field is present but empty #22
=> Team owner field was empty

README.md, ff_espn_api/box_score.py, setup.py
This package version 1.1.0 should be stable for 2019 ESPN API Season.
closes #28
=> Update box score live scoring#28

ff_espn_api/league.py, setup.py, tests/unit/test_league.py
code and test for power rankings week optional
=> Power rankings week optional#46

README.md, ff_espn_api/league.py
Added an option to use your espn username and password instead of searching for the swid and s2 variables. Good work on this!
=> Add authentication

README.md
=> Clean up Readme and transfer usage and api to wiki

ff_espn_api/box_score.py
=> Fix box score when team has bye week

ff_espn_api/activity.py, ff_espn_api/constant.py, ff_espn_api/league.py, ff_espn_api/matchup.py, tests/unit/test_league.py
Fixes bye week for scoreboard #50 
Adds filter and date to recent activity #71
=> Fixes scoreboard away. Add filter and date to recent activity

espn_api/football/box_player.py
=> Fix pro pos rank#93

espn_api/requests/espn_requests.py, setup.py
=> Update get player api call #102

espn_api/football/box_player.py, setup.py
=> Player Applied Stats key error

espn_api/football/box_player.py, setup.py
=> Default stats if week not found

espn_api/base_settings.py, espn_api/basketball/league.py, espn_api/basketball/team.py, espn_api/football/league.py, espn_api/football/team.py
=> Team Division Names

espn_api/base_league.py, espn_api/football/league.py
=> Player Info Bug Temp Fix

espn_api/football/player.py
=> Football player injury

espn_api/football/constant.py, espn_api/football/league.py, tests/football/unit/test_league.py
=> Update free agent input

espn_api/base_league.py, espn_api/basketball/team.py, espn_api/football/box_player.py, espn_api/football/box_score.py, espn_api/football/league.py, espn_api/football/player.py, espn_api/football/team.py, tests/football/unit/test_league.py
Fixes #134 and also addresses #131
=> Add Player Total Points

espn_api/basketball/constant.py, espn_api/football/constant.py, espn_api/football/league.py, tests/football/unit/test_league.py
=> Fix Power Rankings for Team IDs greater than team size

espn_api/basketball/team.py, espn_api/football/team.py
=> Add Team Ties

espn_api/basketball/constant.py, espn_api/basketball/league.py, espn_api/basketball/player.py, tests/basketball/integration/test_league.py
=> Basketball Free Agents

espn_api/base_league.py, tests/football/integration/test_league.py
Hopefully will fix #57 #78 and #85
=> 2 Week Playoff Matchup Period

espn_api/base_league.py, espn_api/base_settings.py, espn_api/football/box_score.py, espn_api/football/league.py, tests/football/integration/test_league.py
=> Box Score Fix 2 Week Playoffs

espn_api/basketball/matchup.py, setup.py
=> Fix Basketball Matchup Stat bug

espn_api/football/activity.py, setup.py
=> Recent activity faab

espn_api/basketball/player.py
Fixes #178 and adds `injured` field to player object
=> Fix Basketball Player Injury Status

espn_api/basketball/league.py
=> Handle No Home Team in Matchup

espn_api/baseball/matchup.py, espn_api/baseball/team.py, setup.py
=> Baseball Remove stat from team/matchup

espn_api/baseball/constant.py
Howdy!
A few months ago I forked the project in attempt to implement the fantasy baseball wrapper. I quickly lost motivation however, but did make quite a bit of progress reverse engineering the schema. I saw recently that someone else had contributed and I felt I might as well share what I discovered on my own. If you are not comfortable with merging changes from me directly, feel free to let someone else do so. Otherwise, let me know if you want me to do any additional work.
=> More mappings for baseball wrapper

.github/workflows/espn-api-test.yml, .github/workflows/espn-api.yml, setup.py
=> Update NumPy version

espn_api/base_league.py, espn_api/football/league.py
=> Football Free Agent Fix Off Season Lookup

espn_api/basketball/box_score.py
=> Basketball Box Score Fix Final Scoring Period

espn_api/basketball/box_score.py, setup.py
=> Fix Basketball Box Score Final Scoring Period Away

espn_api/football/league.py, espn_api/football/pick.py
Modified league.py and pick.py to add the nomination team to the pick class.
=> Added Nomination Team to the Pick Class

espn_api/hockey/constant.py, espn_api/hockey/player.py
=> Add new Seattle Kraken

.github/workflows/espn-api-test.yml, espn_api/hockey/constant.py, espn_api/hockey/player.py, tests/hockey/unit/test_league.py, tests/hockey/unit/test_player.py, tests/hockey/unit/test_team.py
Fixes #249 and #250 
Also enables tests for hockey
=> Fix Hockey Player Position

espn_api/football/team.py, espn_api/requests/espn_requests.py
=> Add Football Team Playoff Pct

espn_api/football/team.py
Issue #308, Replace FB Team Outcome with W/L/U
=> Football Team Outcomes to W/L/U

espn_api/basketball/box_score.py
BB fix #298  key error for box score team. This happens for total season points league
=> Basketball Box Score Winner Index Key

espn_api/football/league.py
Fixes #311 Football `player_info` functionality that needed to update filter with new added game.
=> Football Player Info Filtering Week 1

espn_api/football/team.py, setup.py
=> Add Transaction Info to Football Team

espn_api/baseball/player.py
Baseball player handle unknown position and hopefully fixes #341
=> Baseball Player Handle Unknown Position

espn_api/football/box_score.py, espn_api/football/matchup.py, tests/football/integration/test_league.py
Fixes #352 , thanks @zbloss for initial PR and catching this bug!
=> Fix FB Playoff Field

espn_api/football/player.py, tests/football/unit/test_league.py
=> FB Add Player Ownership

espn_api/football/player.py
I've added ``onTeamId`` to the player object.
=> Add onTeamId to player object

espn_api/football/box_score.py
Fixes #279 and clean up some of box score logic
=> FB Caculate Box Score Projected

espn_api/basketball/league.py, espn_api/hockey/league.py, espn_api/wbasketball/league.py, tests/hockey/integration/test_league.py
=> Remove start date from league class

espn_api/football/box_player.py
=> Football Box Player Game Date

espn_api/football/box_player.py
=> FB Player Bye Week

espn_api/base_league.py, espn_api/basketball/league.py, espn_api/basketball/player.py, espn_api/football/league.py, espn_api/requests/espn_requests.py, tests/basketball/integration/test_league.py
Adds player schedule for #289 and  player info funcitonality will get every game stat for a player #315
=> Basketball Player Info and Schedule

espn_api/football/box_score.py
=> Football Fix Box Score Team Score

espn_api/basketball/matchup.py, espn_api/basketball/player.py, espn_api/basketball/team.py
Fixes #416, handle unknown stat.
=> Basketball Handle Unknown Stat Id

espn_api/basketball/matchup.py
=> Fix Basketball Matchup Bye Week

espn_api/basketball/box_score.py
=> Basketball Box Score Home Team not Present

.github/workflows/package-release.yml, pyproject.toml
=> Publish Wheel, Simple .toml file

espn_api/football/team.py
=> Support new team names

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, espn_api/base_league.py, espn_api/baseball/team.py, espn_api/basketball/team.py, espn_api/football/pick.py, espn_api/football/team.py, espn_api/hockey/__init__.py, espn_api/hockey/member.py, espn_api/hockey/team.py, espn_api/wbasketball/team.py, tests/football/unit/test_league.py, tests/hockey/unit/test_team.py
This updates all Team classes with new name field and removes owner object. Owner field now doesn't provide any additional information for the team. It seems like ESPN recently removed the `firstName` and `lastName` field from members object.
fixes #469
=> Fix Team Data Change

espn_api/base_league.py
=> Fix Multiple Team Owners

espn_api/football/player.py
Fixes #571, thanks @russellkt for investigation and solution!
=> Football Fix Current Week Player Projected Points Stats

espn_api/football/team.py
=> FB Team Waiver Rank

espn_api/hockey/player.py
=> Hockey: Fix Key Error in Player Stats

espn_api/football/team.py
=> Football Add Move to IR in Team Class

espn_api/baseball/player.py
=> Baseball: Add percent owned and status to player object

espn_api/wbasketball/constant.py
Fixes https://github.com/cwendt94/espn-api/issues/645
=> #645 - Add GS Valkyries to WNBA Pro team map
